export default {
  edited: '已编辑',
  sceneBackgroundsKeys: {
      key1: '待机状态',
      key2: '行走过程',
      key3: '到达目的地',
      key4: '任务完成'
  },
  robot: '机器人',
  asrTaskInterruptSwitch: '行走中询问',
  deviceAsr: '语音配置',
  asrSwitch: '语音对话',
  scenePictures: '多场景表情图片',
  scenePicturesKeys: {
      cover: '首页',
      cruise: '巡游中',
      guide: '引领中',
      charge: '充电中',
      missTalk: '对话未命中',
      hitTalk: '对话命中'
  },
  guideThemeName: '迎宾主题',
  character: '形象名称',
  DaXiaoWu: '达小舞（电音女声)',
  SiQi_Blue: '蓝色职业装',
  SchoolGirl_White: '校园服装',
  CloudMinds: '达闼',
  'Cloud Ginger Lite & Patrol': 'Cloud Ginger Lite/Cloud Patrol',
  pitchLow: '低',
  pitchMedium: '中',
  pitchHigh: '高',
  disinfectDuration: '消毒时长',
  wakeUpWordTip: '多个词语用\'|\'分隔。每个为2-6个汉字或2-4个英文单词(泰文没有限制)。示例，唤醒词可以设置成一段全部为中文的：小达小达|你好小达。或者全部是英文的：Hi XiaoDa|Hi Da。又或者全为泰文的：สวัสดีเสี่ยวต้า。注：只有2-3个字的唤醒词会导致误唤醒。',
  checkStrategyDataDuration: '请从早到晚依次选择时间段，且时间段不能交叉不能跨天。',
  urlFormatter: 'URL格式错误，需(http(s)://开头)。',
  searchName: '搜索分类名称',
  ttsTip: '多条语句使用&&分隔',
  types: {
    selfCheckTts: '开机自检',
    dinnerTts: '送餐',
    chargeTts: '一键回充',
    cruiseTts: '巡游',
    barrierTts: '遇障',
    elevatorTts: '电梯',
    deviceSettingTts: '设置',
    deliveryTts: '送货',
    talkingTts: '对话'
  },
  personThreshold: '人员阈值',
  helmetThreshold: '安全帽阈值',
  'asrSwitch-info': '开启后，用户可与机器人进行语音对话',
  'asrTaskInterruptTipsSwitch-info': '任务中打断是否弹出暂停框',
  // comment
  'asrTaskInterruptSwitch-info': '开启后，行走中允许语\n音问询'
}